#:import SMatStrm StaticUO.SMatStrm
#:import SMixer StaticUO.SMixer
#:import SFlash StaticUO.SFlash

<SSPopUp>:
    id:popup
    title: "SIMULATION SETTINGS"
    size_hint:(0.5,0.7)
    pos_hint:{'center_x': 0.5, 'center_y': 0.5}
    opacity: 0.8
    auto_dismiss: True
    GridLayout:
        cols:1
        BoxLayout:
            TabbedPanel:
                size_hint: 0.7,1
                pos_hint: {'top':1}
                do_default_tab: False
                tab_width: self.parent.width/4
                tab_height: 30
                TabbedPanelItem:
                    text: 'General'
                    BoxLayout:
                        orientation: 'vertical'
                        GridLayout:
                            cols:2
                            Label:
                                text: "Simulation Interval"
                            Label:
                                text: " "
                            Label:
                                text: "Start Time: "
                            TextInput:
                                id:start_time
                                size_hint_y:None
                                height:self.parent.height/4
                                valign:'top'
                                font_size:12
                                multiline:False
                            Label:
                                text: "Stop Time: "
                            TextInput:
                                id:stop_time
                                size_hint_y:None
                                height:self.parent.height/4
                                valign:'top'
                                font_size:12
                                multiline:False
                            Spinner:
                                id: interval_type
                                text:"Select"
                                values: ("Number of Intervals","Interval")
                                size_hint_y: None
                                height: self.parent.height/4
                            TextInput:
                                id:interval
                                size_hint_y:None
                                height:self.parent.height/4
                                valign:'top'
                                font_size:12
                                multiline:False
                            Label:
                                text: "Integration"
                            Label:
                                text: " "
                            Label:
                                text: "Method"
                            Spinner:
                                id: method
                                text:"Select"
                                values: ("euler","heun","rungekutte","impeuler","trapezoid","irksco","dassl","ida","rungekuttaSsc","symSolver","symSolverSsc","qss","optimazation")
                                size_hint_y: None
                                height: self.parent.height/4
                            Label:
                                text: "Tolerance"
                            TextInput:
                                id:tolerance
                                size_hint_y:None
                                height:self.parent.height/4
                                valign:'top'
                                font_size:12
                                multiline:False
                            Label:
                                text: "Jacobian"
                            Spinner:
                                id: output_format
                                text:"Select"
                                values: (" ","coloredNumerical","internalNumerical","coloredSymbolical","numerical","symbolical","kluSparse")
                                size_hint_y: None
                                height: self.parent.height/6
                            Label:
                                text: "DASSL/IDA Options"
                            Label:
                                text: " "
                            CheckBox:
                                id: root_finding
                                active: True
                            Label:
                                text: "Root Finding"
                            CheckBox:
                                id: restart_after_event
                            Label:
                                text: "Restart after Event"
                            Label:
                                text: "Initial Step Size"
                            TextInput:
                                id: initial_step_size
                                size_hint_y:None
                                height:self.parent.height/4
                                valign:'top'
                                font_size:12
                                multiline:False
                            Label:
                                text: "Maximum Step Size"
                            TextInput:
                                id: maximum_step_size
                                size_hint_y:None
                                height:self.parent.height/4
                                valign:'top'
                                font_size:12
                                multiline:False
                            Label:
                                text: "Maximum Integration Order"
                            TextInput:
                                id: maximum_integration_order
                                size_hint_y:None
                                height:self.parent.height/4
                                valign:'top'
                                font_size:12
                                multiline:False
                            Label:
                                text: "Compiler Flags (Optional)"
                            TextInput:
                                id: compiler_flags
                                size_hint_y:None
                                height:self.parent.height/4
                                valign:'top'
                                font_size:12
                                multiline:False
                            Label:
                                text: "No of Processors "
                            TextInput:
                                id: no_of_processors
                                size_hint_y:None
                                height:self.parent.height/4
                                valign:'top'
                                font_size:12
                                multiline:False
                            CheckBox:
                                id: build_only
                            Label:
                                text: "Build Only"
                            CheckBox:
                                id: launch_transformatonal_debugger
                            Label:
                                text: "Launch Transformational Debugger"
                            CheckBox:
                                id: launch_algorithmic_debugger
                            Label:
                                text: "Launch Algorithmic Debugger"
                            CheckBox:
                                id: launch_animation
                            Label:
                                text: "Launch Animation"
                TabbedPanelItem:
                    text: 'Output'
                    BoxLayout:
                        orientation: 'vertical'
                        GridLayout:
                            cols:2
                            Label:
                                text: "Output Format"
                            Spinner:
                                id: output_format
                                text:"Select"
                                values: ("mat","csv","plt")
                                size_hint_y: None
                                height: self.parent.height/6
                            Label:
                                text: "File Name Prefix (Optional)"
                            TextInput:
                                id:file_name_prefix
                                size_hint_y:None
                                height:self.parent.height/6
                                valign:'top'
                                font_size:12
                                multiline:False
                            Label:
                                text: "Result File (Optional)"
                            TextInput:
                                id:result_file
                                size_hint_y:None
                                height:self.parent.height/6
                                valign:'top'
                                font_size:12
                                multiline:False
                            Label:
                                text: "Variable Filter (Optional)"
                            TextInput:
                                id:variable_filter
                                size_hint_y:None
                                height:self.parent.height/6
                                valign:'top'
                                font_size:12
                                multiline:False
                            CheckBox:
                                id: protected_variables
                                active: False
                            Label:
                                text: "Protected Variables"
                            CheckBox:
                                id: equidistant_time_grid
                                active: True
                            Label:
                                text: "Equidistant Time Grid"
                            CheckBox:
                                id: store_variables_at_events
                                active: True
                            Label:
                                text: "Store Variables at Events"
                            CheckBox:
                                id:show_generated_files
                            Label:
                                text: "Show Generated Files"

                TabbedPanelItem:
                    text: 'Simulation Flags'
                    ScrollView:
                        BoxLayout:
                            orientation: 'vertical'
                            GridLayout:
                                cols:2
                                Label:
                                    text: "Output Format 1"
                                TextInput:
                                    id:output_format
                                    size_hint_y:None
                                    height:self.parent.height/6
                                    valign:'top'
                                    font_size:12
                                    multiline:False
                                Label:
                                    text: "Output Format 2"
                                TextInput:
                                    id:output_format
                                    size_hint_y:None
                                    height:self.parent.height/6
                                    valign:'top'
                                    font_size:12
                                    multiline:False
                                Label:
                                    text: "Output Format 3"
                                TextInput:
                                    id:output_format
                                    size_hint_y:None
                                    height:self.parent.height/6
                                    valign:'top'
                                    font_size:12
                                    multiline:False
                                Label:
                                    text: "Output Format 4"
                                TextInput:
                                    id:output_format
                                    size_hint_y:None
                                    height:self.parent.height/6
                                    valign:'top'
                                    font_size:12
                                    multiline:False
                                Label:
                                    text: "Output Format 5"
                                TextInput:
                                    id:output_format
                                    size_hint_y:None
                                    height:self.parent.height/6
                                    valign:'top'
                                    font_size:12
                                    multiline:False
                                Label:
                                    text: "Output Format 6"
                                TextInput:
                                    id:output_format
                                    size_hint_y:None
                                    height:self.parent.height/6
                                    valign:'top'
                                    font_size:12
                                    multiline:False
                                Label:
                                    text: "Output Format"
                                TextInput:
                                    id:output_format
                                    size_hint_y:None
                                    height:self.parent.height/6
                                    valign:'top'
                                    font_size:12
                                    multiline:False
                                Label:
                                    text: "Output Format x"
                                TextInput:
                                    id:output_format
                                    size_hint_y:None
                                    height:self.parent.height/6
                                    valign:'top'
                                    font_size:12
                                    multiline:False
                TabbedPanelItem:
                    text: 'Archived Simulations'
        GridLayout:
            cols:2
            CheckBox:
                id: save_expt_anntn
                active: True
            Label:
                text: "Save experiment annotation inside model"
            CheckBox:
                id: save_om_sim_flag
            Label:
                text: "Save OpenModelica Simulationflag"
            Button:
                id: Sim_But
                text: "SIMULATE"
                height:self.parent.height/5
            Label:
                text: "Hello"

<SPopUp>:
    title: "SIMULATION STATUS"
    size_hint:(0.7,0.25)
    auto_dismiss: False
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    opacity: 0.8
    FloatLayout:
        ProgressBar:
            id:ProgBar
            size_hint: 1,0.6
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            value: 50
            max: 100
        Label:
            id:status
            text: 'Loading...'
            size_hint: 1,0.6
            pos_hint: {'center_x': 0.5, 'center_y': 0.12}    

<MenuButton>
    size_hint_y:None
    height:20
    background_normal:''
    background_color:(0.2,0.2,0.2,1)
    halign:'left'
    size_hint_x:None
    width:300
    padding:[10,2]
<MButton@Button>:
    size_hint_x:None
    background_normal:''
    background_color:(0.2,0.2,0.2,0.7)
<M2Button@Button>:
    size_hint_x:None
    background_normal:''
    background_color:(0.3,0.3,0.3,0.7)
<OmWidget>:
    cols:1
    spacing:2.3
    size_hint_y:None
    size_hint:(1,1)
    size:(900,400)
    pos_hint:{'center_x': .5, 'center_y': .5}
    canvas:
        Color:
            rgb: 47 / 255., 167 / 255., 212 / 255., 1.
        Rectangle:
            pos:self.pos
            size:self.size
    BoxLayout:
        size_hint_y:None
        size:(0,30)
        canvas:
            Color:
                rgb: 0.2,0.2,0.2
            Rectangle:
                pos:self.pos
                size:self.size
        MButton:
            width:40
            text:'File'
            on_release:root.filedropdown.open(*args)
        MButton:
            width:40
            text:'Edit'
            on_release:root.editdropdown.open(*args)
        MButton:
            width:60
            text:'Insert'
            on_release:root.insertdropdown.open(*args)
        MButton:
            width:50
            text:'Tools'
            on_release:root.toolsdropdown.open(*args)
        MButton:
            width:70
            text:'Utilities'
            on_release:root.utilitiesdropdown.open(*args)
        MButton:
            width:100
            text:'Optimization'
            on_release:root.optimizationdropdown.open(*args)
        MButton:
            width:70
            text:'Scripts'
            on_release:root.scriptsdropdown.open(*args)
        MButton:
            width:70
            text:'Results'
            on_release:root.resultsdropdown.open(*args)
        MButton:
            width:70
            text:'Plugins'
            on_release:root.pluginsdropdown.open(*args)
        MButton:
            width:70
            text:'Windows'
            on_release:root.windowsdropdown.open(*args)
        MButton:
            width:40
            text:'View'
            on_release:root.viewdropdown.open(*args)
        MButton:
            width:40
            text:'Help'
            on_release:root.helpdropdown.open(*args)
    BoxLayout:
        size_hint_y: None
        size:(0, 30)
        canvas:
            Color:
                rgb: 0.3,0.3,0.3,1
            Rectangle:
                pos:self.pos
                size:self.size
        BoxLayout:
            size_hint_x:0.5
            M2Button:
                width:130
                text:'Compounds'
                on_press:root.CompPop(*args)
            M2Button:
                width:150
                text:'Thermodynamics'
                on_press:root.ThermoPop(*args)
        StackLayout:
            orientation: 'rl-tb'
            size_hint_y: None
            size_hint_x:0.5
            size:(0, 30)
            M2Button:
                text:'COM'
                pos_hint:{'':0}
                width:50
                on_press: root.compile(*args)
            M2Button:
                text:'SIM'
                width:50
                on_press: root.SimulationSettings(*args)
    BoxLayout:
        size_y_hint: None
        FloatLayout:
            id:b1
            size_hint:(0.8,1)
            canvas:
                Color:
                    rgba: (1,1,1,1)
                Rectangle:
                    size: self.size
                    pos: self.pos
        BoxLayout:
            size_hint:(0.2,1)
            orientation:'vertical'
            canvas:
                Color:
                    rgb: 0.1,0.1,0.1
                Rectangle:
                    pos:self.pos
                    size:self.size
            BoxLayout:
                padding: 10
                spacing: 5
                size_hint:(1,0.9)
                SMixer:
                    on_included: root.add_but(*args)
                SMatStrm:
                    on_included: root.add_but(*args)
                SFlash:
                    on_included: root.add_but(*args)






